services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Neominal123!
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Neominal123! -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  taskflow.api:
    image: ${DOCKER_REGISTRY-}taskflowapi
    build:
      context: .
      dockerfile: src/TaskFlow.API/Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=TaskFlowDb;User Id=sa;Password=Neominal123!;TrustServerCertificate=True;
